### ISSUE TITLE
getState is not a function

### ISSUE THREAD

**Issue by cserrurier-norauto** [adobe/adobe-client-data-layer#132]
### Expected Behaviour
Retrieve information from the data layer and trigger rules from the data pushed in the object
### Actual Behaviour
No information is returned because the getState function is no longer recognized
### Reproduce Scenario (including but not limited to)
update the extension ACDL and test the rules
#### Steps to Reproduce
See Reproduce Scenario
#### Platform and Version
Last version of the ACDL extension

**Comment by cserrurier-norauto** [comment]
Update : 
the problem is that Launch is sent before the initialization of the dataLayer. Let's fix this and see if everything is ok

**Comment by sandipupadhyay** [comment]
Unfortunately, even after the Project initialization (i.e. dataLayer already being instantiated) we get the below error-
![getState_error](https://user-images.githubusercontent.com/39223740/148520723-25003678-135a-4037-b2eb-e530da268fd1.png)

Also, the console throws something like below once the React application has been bootstrapped -
![image](https://user-images.githubusercontent.com/39223740/148520999-fcdcc23d-3663-4a69-8844-0c0a3c458eca.png)

Not sure because of this the getState() giver error or something else. I have installed the 'adobe-datalayer.min.js' through Node - "@adobe/adobe-client-data-layer": "^2.0.2", 

It would be very kind of you If you could assist me on this issue

**Comment by gabrielwalt** [comment]
This typically happens when you try to access the data layer before it being loaded. For pages to load faster, it's usually not recommended to load the data layer in a blocking manner, but rather asynchronously. And because of that, you cannot guarantee that the data layer has already been loaded when your script is trying to access it.

Therefore, you should wrap all your code into a callback function that the data layer will call once it's loaded:
```javascript
window.adobeDataLayer = window.adobeDataLayer || [];
window.adobeDataLayer.push(function (dl) {
    var state = dl.getState();
    console.log(state);
});
```
