### ISSUE TITLE
Listener Order

### ISSUE THREAD

**Issue by klcodanr** [adobe/adobe-client-data-layer#43]
### Expected Behaviour

At times you may want to control listener order, e.g. have a particular Listener executed first / last / anywhere in between. For example, if you have a listener that's performing some sort of calculation before data is passed to Analytics. You'd want to ensure this is executed before the Analytics listener.

I would expect there's be some way to pass an order parameter with the listener to control the execution order. With something like 0 being default,  MAX_INT listeners executing first and MIN_INT listeners executing last.

### Actual Behaviour

No order specifier is available.

### Reproduce Scenario (including but not limited to)

N/A

#### Steps to Reproduce

N/A

#### Platform and Version

1.0.0.beta2

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

**Comment by gabrielwalt** [comment]
It is not possible for the listeners to be called in a different order than the one in which they got registered, because of the asynchronous nature of how the script can be loaded.

```javascript
// Let's say that the following happens prior to the data layer script being loaded:
adobeDataLayer.push({ test: "foo" });
// The following line adds a callback to the data layer array that will be executed once
// it has loaded so that we can ensure that accessing the addEventListener method before
// the script has loaded doesn't fail:
adobeDataLayer.push(function (dl) {
    dl.addEventListener("adobeDataLayer:change", function () {
        console.log("listener 1 fired - test=" + dl.getState("test"));
    });
});
…
// Let's say that at this point, the layer script got loaded.
// this then logs: "listener 1 fired - test=foo"
…
// If a second listener then gets registered after the data layer script initialized, it then comes
// too late to have any chance of being executed prior to the previous listener
adobeDataLayer.push(function (dl) {
    dl.addEventListener("adobeDataLayer:change", function () {
        console.log("listener 2 fired - test=" + dl.getState("test"));
    });
});
// this then logs: "listener 2 fired - test=foo"
```

Also, if listeners of some event modify data, this modification will be processed only after all the listeners of this event have been called. So even executing the listeners in the right order doesn't allow one listener to modify the data for the other listeners.

```javascript
adobeDataLayer.push(function(dl) {
    // A first listener appends the "bar" string to the "test" variable when "some event" happens.
    dl.addEventListener("some event", function() {
        dl.push({  test: dl.getState("test") + "bar" });
    });
    // A second listener logs the "test" string when "some event" happens.
    dl.addEventListener("some event", function() {
        console.log("test = " + dl.getState("test"));
    });
    // Then, let's add an event that writes a "test" string into the data layer:
    adobeDataLayer.push({
        event: "some event",
        test: "foo"
    });
    // logs: "test = foo" (and not "test = foobar")
});
```

But I get your point, you want to modify the data before it is being sent to analytics. This, however, will have to happen in the logic that retrieves the data from the data layer and sends it to whatever backend you want. This is where we need hooks to map the data to a different format, and to validate it. I can imagine a Launch extension that is specific to this data layer to be the right place to do that.

Therefore closing this for now, but the overall need won't get forgotten.
