### ISSUE TITLE
Reduce size of minified Data Layer script

### ISSUE THREAD

**Issue by bartoszglow** [adobe/adobe-client-data-layer#57]
The Data layer will be provided with Launch as part of the additional extension. This script will be included on the customer's pages so there is a business need to reduce the size of the final script as much as possible.

A similar script provided by Google (Event Driven Data Layer) has a size of 2kB.

After short verification, it seems that the main problem is Lodash dependency:
- `lodash.clonedeep` is 8.9kB
- `lodash.mergewith` is 9.8kB
- `lodash.get` is 4.4kB

Data Layer script without Lodash is about 10kB.

Proposal:
https://github.com/kolodny/immutability-helper could replace `clonedeep` and `mergewith`

**Comment by vladbailescu** [comment]
Lodash recommends against _per-method packages_ (see https://lodash.com/per-method-packages):

> [..] use of these packages is discouraged and they will be removed in v5.

Instead, we should import methods:

> Don't worry—if you import or require methods directly, e.g. const throttle = require('lodash/throttle'), only the subset of lodash code your package uses will be bundled in projects that use your package.

**Comment by Aaronius** [comment]
One option you have that would have a decent impact on size is to not use prototypal inheritance and es6 classes, since it results in a lot of code that isn't minifiable and might not be providing much value anyway (e.g., I don't think you're leveraging polymorphism). If you were to use the revealing module pattern instead, you wouldn't have to use `this.longPropertyName` or `that.longPropertyName` references and you could use functionally-scoped variables instead, which would result in better minification. You also wouldn't have to incur the babel transpilation overhead for the es6 class support. This is the approach we took for Turbine (https://github.com/adobe/reactor-turbine) and Alloy (https://github.com/adobe/alloy) with good success.

**Comment by gabrielwalt** [comment]
We might also want to look at https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore.

Regarding the supported browsers, we should align with those Adobe Launch supports:
* Chrome (latest)
* Safari (latest)
* Firefox (latest)
* IE (10 and above)
* Edge (latest)
* iOS Safari (latest)
* Android Chrome (latest)
